if (WIN32)
    include(scripts/win32.cmake)
elseif(MAC)
    include(scripts/mac.cmake)
elseif(IOS)
    include(scripts/ios.cmake)
elseif(LINUX)
    include(scripts/linux.cmake)
elseif(ANDROID)
    include(scripts/android.cmake)
endif()

