#CheckFunctionExists
#CheckIncludeFile
#CheckIncludeFileCXX
#CheckIncludeFiles
#CheckLibraryExists
#CheckStructHasMember
#CheckSymbolExists
#CheckTypeSize
#CheckVariableExists


include(CheckVariableExists)
check_variable_exists(timezone HAVE_TIMEZONE)

include(CheckSymbolExists)
check_symbol_exists(socklen_t sys/socket.h HAVE_SOCKLEN_T)
#check_symbol_exists(socklen_t sys/socket.h sys/types.h HAVE_SOCKLEN_T)
check_symbol_exists(AI_ADDRCONFIG netdb.h USE_GAI_ADDRCONFIG)

# Check C types
include(CheckTypeSize)
check_type_size(int         SIZEOF_INT)
check_type_size(long        SIZEOF_LONG)
check_type_size("long long" SIZEOF_LONG_LONG)
check_type_size(off64_t     SIZEOF_OFF64_T)
check_type_size(off_t       SIZEOF_OFF_T)
check_type_size(size_t      SIZEOF_SIZE_T)
check_type_size(ssize_t     SIZEOF_SSIZE_T)
check_type_size(time_t      SIZEOF_TIME_T)
check_type_size(XML_Size    SIZEOF_XML_SIZE)

include(CheckIncludeFiles)
check_include_files("arpa/inet.h" HAVE_ARPA_INET_H)
check_include_files("dlfcn.h" HAVE_DLFCN_H)
check_include_files("errno.h" HAVE_ERRNO_H)
check_include_files("fcntl.h" HAVE_FCNTL_H)
check_include_files("iconv.h" HAVE_ICONV_H)
check_include_files("inttypes.h" HAVE_INTTYPES_H)
check_include_files("libintl.h" HAVE_LIBINTL_H)
check_include_files("limits.h" HAVE_LIMITS_H)
check_include_files("locale.h" HAVE_LOCALE_H)
check_include_files("memory.h" HAVE_MEMORY_H)
check_include_files("netdb.h" HAVE_NETDB_H)
check_include_files("netinet/in.h" HAVE_NETINET_IN_H)
check_include_files("netinet/tcp.h" HAVE_NETINET_TCP_H)
check_include_files("signal.h" HAVE_SIGNAL_H)
check_include_files("stdarg.h" HAVE_STDARG_H)
check_include_files("stdint.h" HAVE_STDINT_H)
check_include_files("stdlib.h" HAVE_STDLIB_H)
check_include_files("strings.h" HAVE_STRINGS_H)
check_include_files("string.h" HAVE_STRING_H)
check_include_files("sys/limits.h" HAVE_SYS_LIMITS_H)
check_include_files("sys/poll.h" HAVE_SYS_POLL_H)
check_include_files("sys/select.h" HAVE_SYS_SELECT_H)
check_include_files("sys/socket.h" HAVE_SYS_SOCKET_H)
check_include_files("sys/stat.h" HAVE_SYS_STAT_H)
check_include_files("sys/time.h" HAVE_SYS_TIME_H)
check_include_files("sys/types.h" HAVE_SYS_TYPES_H)
check_include_files("sys/uio.h" HAVE_SYS_UIO_H)
check_include_files("trio.h" HAVE_TRIO_H)
check_include_files("unistd.h" HAVE_UNISTD_H)
check_include_files("sys/time.h" "time.h" TIME_WITH_SYS_TIME)

include(CheckFunctionExists)
check_function_exists(stpcpy HAVE_DECL_STPCPY)
check_function_exists(strerror_r HAVE_DECL_STRERROR_R)
check_function_exists(fcntl HAVE_FCNTL)
check_function_exists(fstat64 HAVE_FSTAT64)
check_function_exists(gai_strerror HAVE_GAI_STRERROR)
check_function_exists(gethostname HAVE_GETHOSTNAME)
check_function_exists(getnameinfo HAVE_GETNAMEINFO)
check_function_exists(hstrerror HAVE_HSTRERROR)
check_function_exists(getsockopt HAVE_GETSOCKOPT)
check_function_exists(inet_ntop HAVE_INET_NTOP)
check_function_exists(inet_pton HAVE_INET_PTON)
check_function_exists(isatty HAVE_ISATTY)
check_function_exists(lseek64 HAVE_LSEEK64)
check_function_exists(pipe HAVE_PIPE)
check_function_exists(poll HAVE_POLL)
check_function_exists(pthread_mutex_init HAVE_PTHREAD_MUTEX_INIT)
check_function_exists(pthread_mutex_lock HAVE_PTHREAD_MUTEX_LOCK)
check_function_exists(setlocale HAVE_SETLOCALE)
check_function_exists(setsockopt HAVE_SETSOCKOPT)
check_function_exists(setvbuf HAVE_SETVBUF)
check_function_exists(shutdown HAVE_SHUTDOWN)
check_function_exists(signal HAVE_SIGNAL)
check_function_exists(snprintf HAVE_SNPRINTF)
check_function_exists(stpcpy HAVE_STPCPY)
check_function_exists(strcasecmp HAVE_STRCASECMP)
check_function_exists(strerror_r HAVE_STRERROR_R)
check_function_exists(strtoll HAVE_STRTOLL)
check_function_exists(strtoq HAVE_STRTOQ)
check_function_exists(usleep HAVE_USLEEP)
check_function_exists(vsnprintf HAVE_VSNPRINTF)

include(CheckStructHasMember)
check_struct_has_member("struct tm" tm_gmtoff time.h HAVE_STRUCT_TM_TM_GMTOFF)
check_struct_has_member("struct tm" __tm_gmtoff time.h HAVE_STRUCT_TM___TM_GMTOFF)

# set the size of off_t/size_t/ssize_t/time_t
set(NE_FMT_NE_OFF_T NE_FMT_OFF_T)
if (${SIZEOF_OFF_T} EQUAL 4)
    set(NE_FMT_OFF_T \"ld\")
else()
    set(NE_FMT_OFF_T \"lld\")
endif()
if (${SIZEOF_SIZE_T} EQUAL 4)
    set(NE_FMT_SIZE_T \"u\")
else()
    set(NE_FMT_SIZE_T \"lu\")
endif()
if (${SIZEOF_SSIZE_T} EQUAL 4)
    set(NE_FMT_SSIZE_T \"d\")
else()
    set(NE_FMT_SSIZE_T \"ld\")
endif()
if (${SIZEOF_TIME_T} EQUAL 4)
    set(NE_FMT_TIME_T \"d\")
else()
    set(NE_FMT_TIME_T \"ld\")
endif()

if(${USE_GAI_ADDRCONFIG})
    set(USE_GETADDRINFO 1)
endif()

set(STDC_HEADERS 1)
set(_ALL_SOURCE 1)
set(_GNU_SOURCE 1)
set(_POSIX_PTHREAD_SEMANTICS 1)
set(_TANDEM_SOURCE 1)
set(__EXTENSIONS__ 1)

set(NEON_IS_LIBRARY 1)
set(NE_DEBUGGING 1)
#set(NE_HAVE_DAV 1)

set(NEON_VERSION \"0.30.0\")
set(NE_VERSION_MAJOR "\(0\)")
set(NE_VERSION_MINOR "\(30\)")
set(NE_VERSION_PATCH "\(0\)")
set(PACKAGE_BUGREPORT \"neon@lists.manyfish.co.uk\")
set(PACKAGE_NAME \"neon\")
set(PACKAGE_STRING \"neon\ 0.30.0\")
set(PACKAGE_TARNAME \"neon\")
set(PACKAGE_URL \"\")
set(PACKAGE_VERSION \"0.30.0\")


configure_file(config.h.cmake.in config.h)
include_directories(${PROJECT_BINARY_DIR}/misc/libneon)
